[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "syntactic"
version = "0.1.0"
description = "A very stupid syntatic analysis, that only checks for assertion errors."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "jpamb",
  "tree-sitter>=0.26.0",
  "tree-sitter-java>=0.23.5",
]


[project.scripts]
syntactic-treesitter = "syntactic_treesitter:main"
syntactic-regex = "syntactic_regex:main"
syntactic-bytecode = "syntactic_bytecode:main"

[tool.uv.sources]
jpamb = { path = "../../", editable = true }

[dependency-groups]
dev = [
    "jpamb",
    "pytest>=9.1.1",
]
