[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dynamic"
version = "0.1.0"
description = "The start of an interperter"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "jpamb",
]


[project.scripts]
dynamic-interpret = "dynamic:interpret"
dynamic-analyse = "dynamic:analyse"

[tool.uv.sources]
jpamb = { path = "../../", editable = true }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

